dyc3/senior-design

- main.typ
- team-declaration.typ
> add team declaration chapter

- join-process.typ
- protocol.typ
- solution-overview.typ
> update balancer-monolith connection direction

- main.typ
Prof said we need these things or hes gonna take points off.
closes #13 
closes #9
> add doc title page, list of figures and tables

- glossary.yaml
- harness-requirements.typ
> add harness requirements

- room-states.typ
> add section about migrating room state

- dev-plan/dev-plan.typ
> Add dev plan document

- harness-requirements.typ
Fixes issue #30 
Trying to figure out if putting the square on the same line as the requirements is possible
> Add Harness requirements formatting

- main.typ
> indent table of contents

- harness-design.typ
> document harness discovery

- harness-requirements.typ
- main.typ
> linkable test harness requirements

- balancer-requirements.typ
- harness-requirements.typ
- lib/requirements.typ
- main.typ
- use-cases.typ
Also contains all the changes necessary to make it acceptable for week report 6
closes #75
> refactor requirements lib into it's own module

- .github/workflows/build.yml
> upgrade typst to 0.8.0

- balancer-requirements.typ
- lib/requirements.typ
- lib/use-cases.typ
- use-cases.typ
- wip: use case function
- fix use case header layout and formatting
- completely fix use case formatting
- adjust how use cases are rendered in requirements
- add use cases to balancer requirements
- add a requirement
closes #74
> add structured, referencable use cases

- weekly-reports.typ
- add weekly report 7
- update
> add weekly report 7

- lib/use-cases.typ
- main.typ
- use-cases.typ
- user-stories.typ
> add user stories

- balancer-requirements.typ
- harness-requirements.typ
- lib/requirements.typ
- add colors to necessity boxes, remove priority box from builds
- fully remove requirement priorities
as requested by darien
> Remove requirement priorities in favor of just having necessity

- changelog.typ
- lib/misc.typ
- main.typ
- weekly-reports.typ
- add helper for github links, closes #85
- replace existing github links with helper
- add repo links to changelog entries
> add github link helper

- lib/use-cases.typ
- main.typ
- use-cases.typ
> basic and alternate flows for use cases

- balancer-requirements.typ
> add nice to have requirements

- lib/use-cases.typ
- use-cases.typ
> use case elaboration

- main.typ
> make references underlined

- use-cases.typ
> add "Access Diagnostics" use case

- balancer-requirements.typ
- room-states.typ
> clarify what good and bad state is

- harness-requirements.typ
> Add figure labels and captions to test harness example cases

- dev-plan/dev-plan.typ
> format dev plan so it fits better into the doc

- lib/use-cases.typ
- use-cases.typ
> add references from use cases to usecase diagrams

- .github/workflows/build.yml
> upgrade typst to 0.10.0

- team-declaration.typ
> elaborate on what a stateful application is

- glossary.yaml
> add OpenTogetherTube to glossary

- introduction.typ
- main.typ
- team-declaration.typ
> Added intro and name

- team-declaration.typ
- mention the monolith in the mission statement, fixes #169
- mention that the balancer is a reverse proxy, fixes #170
> minor changes to the mission statement

- solution-overview.typ
> elaborate more in description of @Figure::monolith-class-current

- visualization-requirements.typ
Added a few requirements for each specific visualization
> add requirements for each visualization

- balancer-design.typ
> add some missing information to the dev enironment section

- lib/glossary.typ
> render glossary as a typst term list

- team-declaration.typ
- Fixed a minor typo in the mission statement.
> fix minor typo in mission statement

- scripts/get-changed-figures.sh
> add a script to collect all the changed figures for weekly reports

- .github/workflows/build.yml
- .gitignore
- harness-requirements.typ
- makefile
- scripts/lints/figure-labels-match-files.py
- scripts/lints/figure-labels-prefixes-match-content.py
- scripts/lints/lintutil.py
This PR adds some scripts to enforce some naming conventions.
> ci: add some custom lint rules

- expo/expo-abstract.typ
Requiring reviews from everybody.
- Please ensure your name is the way you want it displayed on your name tag.
> add project abstract for innovation expo

- .github/workflows/build.yml
> upgrade typst to 0.11.0

- poster.typ
> Add draft to poster to doc

- visualization-design.typ
update system state to reflect changes made to it.
> update system state to reflect changes

- poster.typ
> poster: update sizes of diagrams, add a bullet point

- main.typ
> add OTT Logo to cover page

- visualization-requirements.typ
> fix some missing punctuation

- visualization-design.typ
> remove other unimportant info from vis design

- visualization-design.typ
> rework vis data gathering sections

- join-process.typ
> minor tweaks join-process

- visualization-design.typ
> force disallow pagebreaks in some areas

- lib/glossary.typ
> fix glossary items with no link having blank lines under them

- motivation.typ
> tweak size of components-monolith to fit on page
